// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: superhero/v1/superhero_api.proto

package superherov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_superhero_v1_superhero_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_superhero_v1_superhero_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_superhero_v1_superhero_api_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Pagina struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagina int32 `protobuf:"varint,1,opt,name=pagina,proto3" json:"pagina,omitempty"`
}

func (x *Pagina) Reset() {
	*x = Pagina{}
	if protoimpl.UnsafeEnabled {
		mi := &file_superhero_v1_superhero_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagina) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagina) ProtoMessage() {}

func (x *Pagina) ProtoReflect() protoreflect.Message {
	mi := &file_superhero_v1_superhero_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagina.ProtoReflect.Descriptor instead.
func (*Pagina) Descriptor() ([]byte, []int) {
	return file_superhero_v1_superhero_api_proto_rawDescGZIP(), []int{1}
}

func (x *Pagina) GetPagina() int32 {
	if x != nil {
		return x.Pagina
	}
	return 0
}

type ListaSuperhero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Superheros []*Superhero `protobuf:"bytes,1,rep,name=superheros,proto3" json:"superheros,omitempty"`
}

func (x *ListaSuperhero) Reset() {
	*x = ListaSuperhero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_superhero_v1_superhero_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListaSuperhero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaSuperhero) ProtoMessage() {}

func (x *ListaSuperhero) ProtoReflect() protoreflect.Message {
	mi := &file_superhero_v1_superhero_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaSuperhero.ProtoReflect.Descriptor instead.
func (*ListaSuperhero) Descriptor() ([]byte, []int) {
	return file_superhero_v1_superhero_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListaSuperhero) GetSuperheros() []*Superhero {
	if x != nil {
		return x.Superheros
	}
	return nil
}

var File_superhero_v1_superhero_api_proto protoreflect.FileDescriptor

var file_superhero_v1_superhero_api_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x20, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x22, 0x49, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x61, 0x53, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x12, 0x37, 0x0a, 0x0a,
	0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x65, 0x72,
	0x68, 0x65, 0x72, 0x6f, 0x73, 0x32, 0xbf, 0x01, 0x0a, 0x0c, 0x53, 0x75, 0x70, 0x65, 0x72, 0x68,
	0x65, 0x72, 0x6f, 0x41, 0x70, 0x69, 0x12, 0x36, 0x0a, 0x05, 0x43, 0x72, 0x65, 0x61, 0x72, 0x12,
	0x17, 0x2e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x1a, 0x14, 0x2e, 0x73, 0x75, 0x70, 0x65, 0x72,
	0x68, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3a,
	0x0a, 0x09, 0x41, 0x63, 0x74, 0x75, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x12, 0x17, 0x2e, 0x73, 0x75,
	0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72,
	0x68, 0x65, 0x72, 0x6f, 0x1a, 0x14, 0x2e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3b, 0x0a, 0x05, 0x4c, 0x69,
	0x73, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x1a, 0x1c, 0x2e, 0x73, 0x75, 0x70, 0x65,
	0x72, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x53, 0x75,
	0x70, 0x65, 0x72, 0x68, 0x65, 0x72, 0x6f, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x75, 0x70, 0x65, 0x72,
	0x68, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x75, 0x70, 0x65, 0x72, 0x68, 0x65, 0x72,
	0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_superhero_v1_superhero_api_proto_rawDescOnce sync.Once
	file_superhero_v1_superhero_api_proto_rawDescData = file_superhero_v1_superhero_api_proto_rawDesc
)

func file_superhero_v1_superhero_api_proto_rawDescGZIP() []byte {
	file_superhero_v1_superhero_api_proto_rawDescOnce.Do(func() {
		file_superhero_v1_superhero_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_superhero_v1_superhero_api_proto_rawDescData)
	})
	return file_superhero_v1_superhero_api_proto_rawDescData
}

var file_superhero_v1_superhero_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_superhero_v1_superhero_api_proto_goTypes = []interface{}{
	(*Result)(nil),         // 0: superhero.v1.Result
	(*Pagina)(nil),         // 1: superhero.v1.Pagina
	(*ListaSuperhero)(nil), // 2: superhero.v1.ListaSuperhero
	(*Superhero)(nil),      // 3: superhero.v1.Superhero
}
var file_superhero_v1_superhero_api_proto_depIdxs = []int32{
	3, // 0: superhero.v1.ListaSuperhero.superheros:type_name -> superhero.v1.Superhero
	3, // 1: superhero.v1.SuperheroApi.Crear:input_type -> superhero.v1.Superhero
	3, // 2: superhero.v1.SuperheroApi.Actulizar:input_type -> superhero.v1.Superhero
	1, // 3: superhero.v1.SuperheroApi.Lista:input_type -> superhero.v1.Pagina
	0, // 4: superhero.v1.SuperheroApi.Crear:output_type -> superhero.v1.Result
	0, // 5: superhero.v1.SuperheroApi.Actulizar:output_type -> superhero.v1.Result
	2, // 6: superhero.v1.SuperheroApi.Lista:output_type -> superhero.v1.ListaSuperhero
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_superhero_v1_superhero_api_proto_init() }
func file_superhero_v1_superhero_api_proto_init() {
	if File_superhero_v1_superhero_api_proto != nil {
		return
	}
	file_superhero_v1_superhero_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_superhero_v1_superhero_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_superhero_v1_superhero_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagina); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_superhero_v1_superhero_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListaSuperhero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_superhero_v1_superhero_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_superhero_v1_superhero_api_proto_goTypes,
		DependencyIndexes: file_superhero_v1_superhero_api_proto_depIdxs,
		MessageInfos:      file_superhero_v1_superhero_api_proto_msgTypes,
	}.Build()
	File_superhero_v1_superhero_api_proto = out.File
	file_superhero_v1_superhero_api_proto_rawDesc = nil
	file_superhero_v1_superhero_api_proto_goTypes = nil
	file_superhero_v1_superhero_api_proto_depIdxs = nil
}
